import 'package:flutter/foundation.dart';

final localeNotifier = ValueNotifier<String>('en');

String tr(String key) {
  final current = localeNotifier.value;
  return _translations[current]?[key] ?? _translations['en']?[key] ?? key;
}

const Map<String, Map<String, String>> _translations = {
  'en': {
    'app_name': 'HisaabKar',
    'dashboard': 'Dashboard',
    'pos': 'Billing',
    'ledger': 'Khaata',
    'inventory': 'Stock',
    'settings': 'Settings',
    'sign_out': 'Sign Out',
    'outstanding_debt': 'OUTSTANDING DEBT',
    'cash_on_hand': 'CASH ON HAND',
    'today_sales': 'TODAY\'S SALES',
    'active_customers': 'ACTIVE CUSTOMERS',
    'recent_activity': 'Recent Activity',
    'top_debtors': 'Top Debtors / Accounts',
    'search_parts': 'Search parts inventory...',
    'manual_part': 'Manual Part',
    'customer_account': 'CUSTOMER ACCOUNT',
    'billing_cart': 'BILLING CART',
    'subtotal': 'Subtotal',
    'discount': 'Discount (Rs.)',
    'payment_type': 'Payment Type',
    'cash_paid': 'Cash Paid',
    'khaata_credit': 'Khaata / Credit',
    'net_total': 'NET TOTAL',
    'pay_print': 'PAY & PRINT RECEIPT',
    'record_khaata': 'RECORD ON KHAATA & PRINT',
    'accounts_directory': 'ACCOUNTS DIRECTORY',
    'new_account': 'New Account',
    'receive_payment': 'Receive Payment (Cr)',
    'give_credit': 'Give Credit (Dr)',
    'account_statement': 'ACCOUNT STATEMENT LOG',
    'back_to_accounts': 'Back to Accounts',
    'no_transactions': 'No transactions found for this account.',
    'save_entry': 'Save Entry',
    'save_customer': 'Save Customer',
    'shop_profile': 'Shop Profile (Invoice Header)',
    'business_name': 'Business / Shop Name',
    'phone_number': 'Phone Number',
    'address': 'Address / Area',
    'supabase_setup': 'Supabase Cloud Setup',
    'save_connect': 'Save & Connect Supabase',
    'currently_offline': 'Currently in Offline Demo Mode',
    'currently_connected': 'Currently Connected to Supabase Cloud',
    'stock_status': 'STOCK STATUS',
    'in_stock': 'In Stock',
    'low_stock': 'Low Stock',
    'out_of_stock': 'Out of Stock',
    'add_new_part': 'Add New Spare Part',
    'edit_stock': 'Edit Stock',
    'reorder_level': 'REORDER STATUS',
    'all': 'All',
    'lubricants': 'Lubricants',
    'filters': 'Filters',
    'electrical': 'Electrical',
    'brakes': 'Brakes',
    'batteries': 'Batteries',
    'reconnecting_msg': 'Database configurations updated. Please restart app to reconnect.',
    'confirm_signout': 'Are you sure you want to sign out of the terminal?',
    'cancel': 'Cancel',
  },
  'ur': {
    'app_name': 'حساب کار',
    'dashboard': 'ڈیش بورڈ',
    'pos': 'بلنگ',
    'ledger': 'کھاتہ',
    'inventory': 'اسٹاک',
    'settings': 'ترتیبات',
    'sign_out': 'لاگ آؤٹ',
    'outstanding_debt': 'کل واجب الادا ادھار',
    'cash_on_hand': 'کیش رقم',
    'today_sales': 'آج کی فروخت',
    'active_customers': 'فعال صارفین',
    'recent_activity': 'حالیہ سرگرمی',
    'top_debtors': 'نمایاں مقروض کھاتے',
    'search_parts': 'پرزہ جات تلاش کریں۔۔۔',
    'manual_part': 'دستی پرزہ',
    'customer_account': 'کسٹمر اکاؤنٹ',
    'billing_cart': 'بلنگ کارٹ',
    'subtotal': 'کل رقم',
    'discount': 'رعایت (روپے)',
    'payment_type': 'ادائیگی کی قسم',
    'cash_paid': 'نقد ادائیگی',
    'khaata_credit': 'کھاتہ / ادھار',
    'net_total': 'کل واجب الادا رقم',
    'pay_print': 'رقم وصول کریں اور پرنٹ کریں',
    'record_khaata': 'کھاتہ درج کریں اور پرنٹ کریں',
    'accounts_directory': 'صارفین کی فہرست',
    'new_account': 'نیا کھاتہ بنائیں',
    'receive_payment': 'ادائیگی وصول کریں',
    'give_credit': 'ادھار دیں',
    'account_statement': 'کھاتہ کا مکمل حساب',
    'back_to_accounts': 'واپس فہرست پر جائیں',
    'no_transactions': 'اس کھاتے کی کوئی سرگرمی نہیں ملی۔',
    'save_entry': 'اندراج محفوظ کریں',
    'save_customer': 'کسٹمر محفوظ کریں',
    'shop_profile': 'دکان کی پروفائل (ہیڈر)',
    'business_name': 'کاروبار / دکان کا نام',
    'phone_number': 'فون نمبر',
    'address': 'پتہ / علاقہ',
    'supabase_setup': 'ڈیٹا بیس کلاؤڈ سیٹ اپ',
    'save_connect': 'محفوظ کریں اور منسلک کریں',
    'currently_offline': 'آف لائن ڈیمو موڈ میں کام کر رہے ہیں',
    'currently_connected': 'ڈیٹا بیس کلاؤڈ سے منسلک ہیں',
    'stock_status': 'اسٹاک کی صورتحال',
    'in_stock': 'دستیاب اسٹاک',
    'low_stock': 'کم اسٹاک',
    'out_of_stock': 'اسٹاک ختم',
    'add_new_part': 'نیا پرزہ شامل کریں',
    'edit_stock': 'اسٹاک تبدیل کریں',
    'reorder_level': 'دوبارہ آرڈر کی ضرورت',
    'all': 'تمام',
    'lubricants': 'لبریکینٹس',
    'filters': 'فلٹرز',
    'electrical': 'الیکٹریکل',
    'brakes': 'بریک',
    'batteries': 'بیٹریاں',
    'reconnecting_msg': 'ڈیٹا بیس ترتیبات تبدیل ہو گ گئیں، براہ کرم ایپ دوبارہ شروع کریں۔',
    'confirm_signout': 'کیا آپ سائن آؤٹ کرنا چاہتے ہیں؟',
    'cancel': 'منسوخ کریں',
  }
};
